application: myapp
version: alpha-001
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: urls.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

builtins:
- deferred: on